const mockList = [
    {
        "url": "https://api.github.com/repos/facebook/react/issues/19828",
        "repository_url": "https://api.github.com/repos/facebook/react",
        "labels_url": "https://api.github.com/repos/facebook/react/issues/19828/labels{/name}",
        "comments_url": "https://api.github.com/repos/facebook/react/issues/19828/comments",
        "events_url": "https://api.github.com/repos/facebook/react/issues/19828/events",
        "html_url": "https://github.com/facebook/react/issues/19828",
        "id": 700679981,
        "node_id": "MDU6SXNzdWU3MDA2Nzk5ODE=",
        "number": 19828,
        "title": "Bug: A menu item in tutorial doesn't get highlighted on click",
        "user": {
            "login": "izdwuut",
            "id": 33417130,
            "node_id": "MDQ6VXNlcjMzNDE3MTMw",
            "avatar_url": "https://avatars3.githubusercontent.com/u/33417130?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/izdwuut",
            "html_url": "https://github.com/izdwuut",
            "followers_url": "https://api.github.com/users/izdwuut/followers",
            "following_url": "https://api.github.com/users/izdwuut/following{/other_user}",
            "gists_url": "https://api.github.com/users/izdwuut/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/izdwuut/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/izdwuut/subscriptions",
            "organizations_url": "https://api.github.com/users/izdwuut/orgs",
            "repos_url": "https://api.github.com/users/izdwuut/repos",
            "events_url": "https://api.github.com/users/izdwuut/events{/privacy}",
            "received_events_url": "https://api.github.com/users/izdwuut/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 155984160,
                "node_id": "MDU6TGFiZWwxNTU5ODQxNjA=",
                "url": "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
                "name": "Status: Unconfirmed",
                "color": "d4c5f9",
                "default": false,
                "description": "A potential issue that we haven't yet confirmed as a bug"
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-09-14T00:25:59Z",
        "updated_at": "2020-09-14T01:07:14Z",
        "closed_at": null,
        "author_association": "NONE",
        "active_lock_reason": null,
        "body": "<!--\r\n  Please provide a clear and concise description of what the bug is. Include\r\n  screenshots if needed. Please test using the latest version of the relevant\r\n  React packages to make sure your issue has not already been fixed.\r\n-->\r\nHi!\r\n\r\nI've been working my way through your marvelous [tutorial](https://reactjs.org/tutorial/tutorial.html) when I've noticed that once you click on `Overview > Inspecting the Starter Code` in menu, the element doesn't get highlighted. It's because you use `<h3 id=\"inspecting-the-starter-code\">...</h3>` instead of `<h2 id=\"inspecting-the-starter-code\">...</h2>` in your markup. This should be a subheader, not header.\r\n\r\nReact version: Doesn't apply.\r\nBrowser: Firefox Developer Edition 81.0b9 (64-bit).\r\n\r\n## Steps To Reproduce\r\n\r\n1. Go to https://reactjs.org/tutorial/tutorial.html.\r\n2. Click on `Overview > Inspecting the Starter Code` menu item.\r\n\r\n\r\n\r\n<!--\r\n  Your bug will get fixed much faster if we can run your code and it doesn't\r\n  have dependencies other than React. Issues without reproduction steps or\r\n  code examples may be immediately closed as not actionable.\r\n-->\r\n\r\nLink to code example: doesn't apply.\r\n\r\n<!--\r\n  Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a\r\n  repository on GitHub, or provide a minimal code example that reproduces the\r\n  problem. You may provide a screenshot of the application if you think it is\r\n  relevant to your bug report. Here are some tips for providing a minimal\r\n  example: https://stackoverflow.com/help/mcve.\r\n-->\r\n\r\n## The current behavior\r\nThe `Overview > Inspecting the Starter Code` menu element doesn't get highlighted on click.\r\n\r\n## The expected behavior\r\nThe `Overview > Inspecting the Starter Code` element should get highlighted on click.",
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/facebook/react/issues/19827",
        "repository_url": "https://api.github.com/repos/facebook/react",
        "labels_url": "https://api.github.com/repos/facebook/react/issues/19827/labels{/name}",
        "comments_url": "https://api.github.com/repos/facebook/react/issues/19827/comments",
        "events_url": "https://api.github.com/repos/facebook/react/issues/19827/events",
        "html_url": "https://github.com/facebook/react/pull/19827",
        "id": 700643819,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NDg2MjM3MTI3",
        "number": 19827,
        "title": "DevTools: Improve browser extension iframe support",
        "user": {
            "login": "omarsy",
            "id": 15034695,
            "node_id": "MDQ6VXNlcjE1MDM0Njk1",
            "avatar_url": "https://avatars0.githubusercontent.com/u/15034695?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/omarsy",
            "html_url": "https://github.com/omarsy",
            "followers_url": "https://api.github.com/users/omarsy/followers",
            "following_url": "https://api.github.com/users/omarsy/following{/other_user}",
            "gists_url": "https://api.github.com/users/omarsy/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/omarsy/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/omarsy/subscriptions",
            "organizations_url": "https://api.github.com/users/omarsy/orgs",
            "repos_url": "https://api.github.com/users/omarsy/repos",
            "events_url": "https://api.github.com/users/omarsy/events{/privacy}",
            "received_events_url": "https://api.github.com/users/omarsy/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 196858374,
                "node_id": "MDU6TGFiZWwxOTY4NTgzNzQ=",
                "url": "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
                "name": "CLA Signed",
                "color": "e7e7e7",
                "default": false,
                "description": null
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 3,
        "created_at": "2020-09-13T20:41:02Z",
        "updated_at": "2020-09-13T21:29:15Z",
        "closed_at": null,
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "pull_request": {
            "url": "https://api.github.com/repos/facebook/react/pulls/19827",
            "html_url": "https://github.com/facebook/react/pull/19827",
            "diff_url": "https://github.com/facebook/react/pull/19827.diff",
            "patch_url": "https://github.com/facebook/react/pull/19827.patch"
        },
        "body": "<!--\r\n  Thanks for submitting a pull request!\r\n  We appreciate you spending the time to work on these changes. Please provide enough information so that others can review your pull request. The three fields below are mandatory.\r\n\r\n  Before submitting a pull request, please make sure the following is done:\r\n\r\n  1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.\r\n  2. Run `yarn` in the repository root.\r\n  3. If you've fixed a bug or added code that should be tested, add tests!\r\n  4. Ensure the test suite passes (`yarn test`). Tip: `yarn test --watch TestName` is helpful in development.\r\n  5. Run `yarn test-prod` to test in the production environment. It supports the same options as `yarn test`.\r\n  6. If you need a debugger, run `yarn debug-test --watch TestName`, open `chrome://inspect`, and press \"Inspect\".\r\n  7. Format your code with [prettier](https://github.com/prettier/prettier) (`yarn prettier`).\r\n  8. Make sure your code lints (`yarn lint`). Tip: `yarn linc` to only check changed files.\r\n  9. Run the [Flow](https://flowtype.org/) type checks (`yarn flow`).\r\n  10. If you haven't already, complete the CLA.\r\n\r\n  Learn more about contributing: https://reactjs.org/docs/how-to-contribute.html\r\n-->\r\n\r\n## Summary\r\nThis pull requests is intended to improve iframe support for devtools browser extensions(#18945), without add a code to  pass the hook through from the parent.\r\n\r\n![image](https://user-images.githubusercontent.com/15034695/93028132-28a57e00-f612-11ea-8e35-4749a2b2d7bc.png)\r\n\r\n<!-- Explain the **motivation** for making this change. What existing problem does the pull request solve? -->\r\n\r\n## Test Plan\r\n\r\n<!-- Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes the user interface. -->\r\n",
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/facebook/react/issues/19825",
        "repository_url": "https://api.github.com/repos/facebook/react",
        "labels_url": "https://api.github.com/repos/facebook/react/issues/19825/labels{/name}",
        "comments_url": "https://api.github.com/repos/facebook/react/issues/19825/comments",
        "events_url": "https://api.github.com/repos/facebook/react/issues/19825/events",
        "html_url": "https://github.com/facebook/react/pull/19825",
        "id": 700511107,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NDg2MTM5MjQy",
        "number": 19825,
        "title": "Updates to grammar, formatting of README file ",
        "user": {
            "login": "thejessicafelts",
            "id": 10212524,
            "node_id": "MDQ6VXNlcjEwMjEyNTI0",
            "avatar_url": "https://avatars0.githubusercontent.com/u/10212524?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/thejessicafelts",
            "html_url": "https://github.com/thejessicafelts",
            "followers_url": "https://api.github.com/users/thejessicafelts/followers",
            "following_url": "https://api.github.com/users/thejessicafelts/following{/other_user}",
            "gists_url": "https://api.github.com/users/thejessicafelts/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/thejessicafelts/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/thejessicafelts/subscriptions",
            "organizations_url": "https://api.github.com/users/thejessicafelts/orgs",
            "repos_url": "https://api.github.com/users/thejessicafelts/repos",
            "events_url": "https://api.github.com/users/thejessicafelts/events{/privacy}",
            "received_events_url": "https://api.github.com/users/thejessicafelts/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 196858374,
                "node_id": "MDU6TGFiZWwxOTY4NTgzNzQ=",
                "url": "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
                "name": "CLA Signed",
                "color": "e7e7e7",
                "default": false,
                "description": null
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 3,
        "created_at": "2020-09-13T06:45:30Z",
        "updated_at": "2020-09-13T14:11:37Z",
        "closed_at": null,
        "author_association": "NONE",
        "active_lock_reason": null,
        "pull_request": {
            "url": "https://api.github.com/repos/facebook/react/pulls/19825",
            "html_url": "https://github.com/facebook/react/pull/19825",
            "diff_url": "https://github.com/facebook/react/pull/19825.diff",
            "patch_url": "https://github.com/facebook/react/pull/19825.patch"
        },
        "body": "Updates to grammar and formatting of the README file.\r\n\r\n## Summary\r\n\r\nWhen reading through the README.md file, I thought some changes could be made to make the file easier to read, and more grammatically correct.\r\n\r\n## Test Plan\r\n\r\nN/A - As this is simply a copy update to a .md file, no test plan was created or needed.\r\n\r\n## CLA\r\n\r\nThe CLA has been completed and signed.\r\n",
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/facebook/react/issues/19823",
        "repository_url": "https://api.github.com/repos/facebook/react",
        "labels_url": "https://api.github.com/repos/facebook/react/issues/19823/labels{/name}",
        "comments_url": "https://api.github.com/repos/facebook/react/issues/19823/comments",
        "events_url": "https://api.github.com/repos/facebook/react/issues/19823/events",
        "html_url": "https://github.com/facebook/react/issues/19823",
        "id": 700183312,
        "node_id": "MDU6SXNzdWU3MDAxODMzMTI=",
        "number": 19823,
        "title": "Feature request: bind event to react hook component. especially for typescript",
        "user": {
            "login": "thinksource",
            "id": 2766693,
            "node_id": "MDQ6VXNlcjI3NjY2OTM=",
            "avatar_url": "https://avatars0.githubusercontent.com/u/2766693?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/thinksource",
            "html_url": "https://github.com/thinksource",
            "followers_url": "https://api.github.com/users/thinksource/followers",
            "following_url": "https://api.github.com/users/thinksource/following{/other_user}",
            "gists_url": "https://api.github.com/users/thinksource/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/thinksource/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/thinksource/subscriptions",
            "organizations_url": "https://api.github.com/users/thinksource/orgs",
            "repos_url": "https://api.github.com/users/thinksource/repos",
            "events_url": "https://api.github.com/users/thinksource/events{/privacy}",
            "received_events_url": "https://api.github.com/users/thinksource/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 155984160,
                "node_id": "MDU6TGFiZWwxNTU5ODQxNjA=",
                "url": "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
                "name": "Status: Unconfirmed",
                "color": "d4c5f9",
                "default": false,
                "description": "A potential issue that we haven't yet confirmed as a bug"
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-09-12T10:29:24Z",
        "updated_at": "2020-09-12T10:29:24Z",
        "closed_at": null,
        "author_association": "NONE",
        "active_lock_reason": null,
        "body": "I have two components the children component will emit 'onchange' event to parent component and the parent hook will deal with this event like:\r\n\r\nparent component.\r\n\r\n```\r\nconst App = ()=>{\r\n    const initvalue=['abc']\r\n    const handleChange(e:InputEvent)=>{\r\n         return e.target.value\r\n    }\r\n    return (\r\n   <>\r\n         <InputArray  value={initvalue} onChange={handleChange}/>\r\n   </>\r\n   )\r\n\r\n}\r\n```\r\nthe children Component like:\r\n\r\n```\r\nconst InputArray = (props: React.HTMLProps<HTMLInputElement>) =>{\r\n     const {fields, onChang}= props\r\n     const ulEl = useRef<HTMLInputElement>(null);\r\n\r\n   useEffect(()=>{\r\n        ulEl.current?.addEventListener('change', props.onChange)\r\n       return (()=>{\r\n                 ulEI.current?.removeEventListener('change', props.onChange)\r\n                 }\r\n              )\r\n\r\n    })\r\n\r\n    return (\r\n    <ul ref={ulEl}>\r\n        <p><button type=\"button\" onClick={addfields}>\r\n            Add \r\n        </button>\r\n        <button type=\"button\" onClick={removefields}>\r\n            remove \r\n        </button></p>\r\n        {fields.map((key, index)=>(<li key={`k${index}`} ><input type=\"text\" value={key} onChange={(val: ChangeEvent<HTMLInputElement>)=>{\r\n            props.values[index]=e.target.value\r\n            emit('change', props.values)  // I just want input can emit an event to UL and UL can deal with InputEvent.\r\n        }}/></li>))}\r\n    </ul>)\r\n}\r\n```\r\nI want the feature react hook can add new eventListener and children input can emit some even to outside.\r\n(esp for typescript as UL is not input-element and it do not have matched types) ",
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/facebook/react/issues/19822",
        "repository_url": "https://api.github.com/repos/facebook/react",
        "labels_url": "https://api.github.com/repos/facebook/react/issues/19822/labels{/name}",
        "comments_url": "https://api.github.com/repos/facebook/react/issues/19822/comments",
        "events_url": "https://api.github.com/repos/facebook/react/issues/19822/events",
        "html_url": "https://github.com/facebook/react/pull/19822",
        "id": 700059290,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NDg1NzQ3OTU4",
        "number": 19822,
        "title": "Updates to grammar, formatting of CoC",
        "user": {
            "login": "thejessicafelts",
            "id": 10212524,
            "node_id": "MDQ6VXNlcjEwMjEyNTI0",
            "avatar_url": "https://avatars0.githubusercontent.com/u/10212524?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/thejessicafelts",
            "html_url": "https://github.com/thejessicafelts",
            "followers_url": "https://api.github.com/users/thejessicafelts/followers",
            "following_url": "https://api.github.com/users/thejessicafelts/following{/other_user}",
            "gists_url": "https://api.github.com/users/thejessicafelts/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/thejessicafelts/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/thejessicafelts/subscriptions",
            "organizations_url": "https://api.github.com/users/thejessicafelts/orgs",
            "repos_url": "https://api.github.com/users/thejessicafelts/repos",
            "events_url": "https://api.github.com/users/thejessicafelts/events{/privacy}",
            "received_events_url": "https://api.github.com/users/thejessicafelts/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 196858374,
                "node_id": "MDU6TGFiZWwxOTY4NTgzNzQ=",
                "url": "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
                "name": "CLA Signed",
                "color": "e7e7e7",
                "default": false,
                "description": null
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 3,
        "created_at": "2020-09-12T05:00:10Z",
        "updated_at": "2020-09-12T05:11:35Z",
        "closed_at": null,
        "author_association": "NONE",
        "active_lock_reason": null,
        "pull_request": {
            "url": "https://api.github.com/repos/facebook/react/pulls/19822",
            "html_url": "https://github.com/facebook/react/pull/19822",
            "diff_url": "https://github.com/facebook/react/pull/19822.diff",
            "patch_url": "https://github.com/facebook/react/pull/19822.patch"
        },
        "body": "Updates to grammar and formatting of the Code of Conduct file.\r\n\r\n## Summary\r\n\r\nWhen reading the Code of Conduct file, I thought some changes could be made to make the file easier to read, and more grammatically correct.\r\n\r\n## Test Plan\r\n\r\nN/A - As this is simply a copy update to a .md file, no test plan was created or needed.\r\n\r\n## CLA\r\nThe CLA has been completed and signed.\r\n",
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/facebook/react/issues/19821",
        "repository_url": "https://api.github.com/repos/facebook/react",
        "labels_url": "https://api.github.com/repos/facebook/react/issues/19821/labels{/name}",
        "comments_url": "https://api.github.com/repos/facebook/react/issues/19821/comments",
        "events_url": "https://api.github.com/repos/facebook/react/issues/19821/events",
        "html_url": "https://github.com/facebook/react/pull/19821",
        "id": 699612354,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NDg1MzM2MDY2",
        "number": 19821,
        "title": "Bump node-fetch from 1.6.3 to 2.6.1 in /fixtures/ssr",
        "user": {
            "login": "dependabot[bot]",
            "id": 49699333,
            "node_id": "MDM6Qm90NDk2OTkzMzM=",
            "avatar_url": "https://avatars0.githubusercontent.com/in/29110?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/dependabot%5Bbot%5D",
            "html_url": "https://github.com/apps/dependabot",
            "followers_url": "https://api.github.com/users/dependabot%5Bbot%5D/followers",
            "following_url": "https://api.github.com/users/dependabot%5Bbot%5D/following{/other_user}",
            "gists_url": "https://api.github.com/users/dependabot%5Bbot%5D/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/dependabot%5Bbot%5D/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/dependabot%5Bbot%5D/subscriptions",
            "organizations_url": "https://api.github.com/users/dependabot%5Bbot%5D/orgs",
            "repos_url": "https://api.github.com/users/dependabot%5Bbot%5D/repos",
            "events_url": "https://api.github.com/users/dependabot%5Bbot%5D/events{/privacy}",
            "received_events_url": "https://api.github.com/users/dependabot%5Bbot%5D/received_events",
            "type": "Bot",
            "site_admin": false
        },
        "labels": [
            {
                "id": 196858374,
                "node_id": "MDU6TGFiZWwxOTY4NTgzNzQ=",
                "url": "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
                "name": "CLA Signed",
                "color": "e7e7e7",
                "default": false,
                "description": null
            },
            {
                "id": 1757816973,
                "node_id": "MDU6TGFiZWwxNzU3ODE2OTcz",
                "url": "https://api.github.com/repos/facebook/react/labels/dependencies",
                "name": "dependencies",
                "color": "0366d6",
                "default": false,
                "description": "Pull requests that update a dependency file"
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 3,
        "created_at": "2020-09-11T18:22:09Z",
        "updated_at": "2020-09-11T18:28:15Z",
        "closed_at": null,
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "pull_request": {
            "url": "https://api.github.com/repos/facebook/react/pulls/19821",
            "html_url": "https://github.com/facebook/react/pull/19821",
            "diff_url": "https://github.com/facebook/react/pull/19821.diff",
            "patch_url": "https://github.com/facebook/react/pull/19821.patch"
        },
        "body": "Bumps [node-fetch](https://github.com/bitinn/node-fetch) from 1.6.3 to 2.6.1.\n<details>\n<summary>Release notes</summary>\n<p><em>Sourced from <a href=\"https://github.com/bitinn/node-fetch/releases\">node-fetch's releases</a>.</em></p>\n<blockquote>\n<h2>v2.6.1</h2>\n<p><strong>This is an important security release. It is strongly recommended to update as soon as possible.</strong></p>\n<p>See <a href=\"https://github.com/node-fetch/node-fetch/blob/master/docs/CHANGELOG.md#v261\">CHANGELOG</a> for details.</p>\n<h2>v2.6.0</h2>\n<p>See <a href=\"https://github.com/bitinn/node-fetch/blob/v2.6.0/CHANGELOG.md#v260\">CHANGELOG</a>.</p>\n<h2>v2.5.0</h2>\n<p>See <a href=\"https://github.com/bitinn/node-fetch/blob/v2.5.0/CHANGELOG.md#v250\">CHANGELOG</a>.</p>\n<h2>v2.4.1</h2>\n<p>See <a href=\"https://github.com/bitinn/node-fetch/blob/v2.4.1/CHANGELOG.md#v241\">CHANGELOG</a>.</p>\n<h2>v2.4.0</h2>\n<p>See <a href=\"https://github.com/bitinn/node-fetch/blob/v2.4.0/CHANGELOG.md#v240\">CHANGELOG</a>.</p>\n<h2>v2.3.0</h2>\n<p>See <a href=\"https://github.com/bitinn/node-fetch/blob/v2.3.0/CHANGELOG.md#v230\">CHANGELOG</a>.</p>\n<h2>v2.2.1</h2>\n<p>See <a href=\"https://github.com/bitinn/node-fetch/blob/v2.2.1/CHANGELOG.md#v221\">CHANGELOG</a>.</p>\n<h2>Version 2.1.2</h2>\n<ul>\n<li>Fix: allow <code>Body</code> methods to work on ArrayBuffer<code>-backed </code>Body` objects</li>\n<li>Fix: reject promise returned by <code>Body</code> methods when the accumulated <code>Buffer</code> exceeds the maximum size</li>\n<li>Fix: support custom <code>Host</code> headers with any casing</li>\n<li>Fix: support importing <code>fetch()</code> from TypeScript in <code>browser.js</code></li>\n<li>Fix: handle the redirect response body properly</li>\n</ul>\n<p>See <a href=\"https://github.com/bitinn/node-fetch/blob/v2.1.2/CHANGELOG.md#v212\">CHANGELOG</a>.</p>\n<h2>Version 2.1.1</h2>\n<p>See <a href=\"https://github.com/bitinn/node-fetch/blob/v2.1.1/CHANGELOG.md#v211\">CHANGELOG</a>.</p>\n<p>Fix packaging errors in version 2.1.0.</p>\n<h2>Version 2.1.0</h2>\n<p>See <a href=\"https://github.com/bitinn/node-fetch/blob/v2.1.0/CHANGELOG.md#v210\">CHANGELOG</a>:</p>\n<ul>\n<li>Enhance: allow using ArrayBuffer as the <code>body</code> of a <code>fetch()</code> or <code>Request</code></li>\n<li>Fix: store HTTP headers of a <code>Headers</code> object internally with the given case, for compatibility with older servers that incorrectly treated header names in a case-sensitive manner</li>\n<li>Fix: silently ignore invalid HTTP headers</li>\n<li>Fix: handle HTTP redirect responses without a <code>Location</code> header just like non-redirect responses</li>\n<li>Fix: include bodies when following a redirection when appropriate</li>\n</ul>\n<h2>Version 2.0.0</h2>\n<p>This is a major release. See <a href=\"https://github.com/bitinn/node-fetch/blob/master/UPGRADE-GUIDE.md\">upgrade guide</a> on how to upgrade from v1.x, and the <a href=\"https://github.com/bitinn/node-fetch/blob/master/CHANGELOG.md\">changelog</a> for all changes.</p>\n<h2>v2.0.0-alpha.9</h2>\n<!-- raw HTML omitted -->\n</blockquote>\n</details>\n<details>\n<summary>Changelog</summary>\n<p><em>Sourced from <a href=\"https://github.com/node-fetch/node-fetch/blob/master/docs/CHANGELOG.md\">node-fetch's changelog</a>.</em></p>\n<blockquote>\n<h2>v2.6.1</h2>\n<p><strong>This is an important security release. It is strongly recommended to update as soon as possible.</strong></p>\n<ul>\n<li>Fix: honor the <code>size</code> option after following a redirect.</li>\n</ul>\n<h2>v2.6.0</h2>\n<ul>\n<li>Enhance: <code>options.agent</code>, it now accepts a function that returns custom http(s).Agent instance based on current URL, see readme for more information.</li>\n<li>Fix: incorrect <code>Content-Length</code> was returned for stream body in 2.5.0 release; note that <code>node-fetch</code> doesn't calculate content length for stream body.</li>\n<li>Fix: <code>Response.url</code> should return empty string instead of <code>null</code> by default.</li>\n</ul>\n<h2>v2.5.0</h2>\n<ul>\n<li>Enhance: <code>Response</code> object now includes <code>redirected</code> property.</li>\n<li>Enhance: <code>fetch()</code> now accepts third-party <code>Blob</code> implementation as body.</li>\n<li>Other: disable <code>package-lock.json</code> generation as we never commit them.</li>\n<li>Other: dev dependency update.</li>\n<li>Other: readme update.</li>\n</ul>\n<h2>v2.4.1</h2>\n<ul>\n<li>Fix: <code>Blob</code> import rule for node &lt; 10, as <code>Readable</code> isn't a named export.</li>\n</ul>\n<h2>v2.4.0</h2>\n<ul>\n<li>Enhance: added <code>Brotli</code> compression support (using node's zlib).</li>\n<li>Enhance: updated <code>Blob</code> implementation per spec.</li>\n<li>Fix: set content type automatically for <code>URLSearchParams</code>.</li>\n<li>Fix: <code>Headers</code> now reject empty header names.</li>\n<li>Fix: test cases, as node 12+ no longer accepts invalid header response.</li>\n</ul>\n<h2>v2.3.0</h2>\n<ul>\n<li>Enhance: added <code>AbortSignal</code> support, with README example.</li>\n<li>Enhance: handle invalid <code>Location</code> header during redirect by rejecting them explicitly with <code>FetchError</code>.</li>\n<li>Fix: update <code>browser.js</code> to support react-native environment, where <code>self</code> isn't available globally.</li>\n</ul>\n<h2>v2.2.1</h2>\n<ul>\n<li>Fix: <code>compress</code> flag shouldn't overwrite existing <code>Accept-Encoding</code> header.</li>\n<li>Fix: multiple <code>import</code> rules, where <code>PassThrough</code> etc. doesn't have a named export when using node &lt;10 and <code>--experimental-modules</code> flag.</li>\n<li>Other: Better README.</li>\n</ul>\n<h2>v2.2.0</h2>\n<ul>\n<li>Enhance: Support all <code>ArrayBuffer</code> view types</li>\n<li>Enhance: Support Web Workers</li>\n<li>Enhance: Support Node.js' <code>--experimental-modules</code> mode; deprecate <code>.es.js</code> file</li>\n<li>Fix: Add <code>__esModule</code> property to the exports object</li>\n</ul>\n<!-- raw HTML omitted -->\n</blockquote>\n</details>\n<details>\n<summary>Commits</summary>\n<ul>\n<li><a href=\"https://github.com/node-fetch/node-fetch/commit/b5e2e41b2b50bf2997720d6125accaf0dd68c0ab\"><code>b5e2e41</code></a> update version number</li>\n<li><a href=\"https://github.com/node-fetch/node-fetch/commit/2358a6c2563d1730a0cdaccc197c611949f6a334\"><code>2358a6c</code></a> Honor the <code>size</code> option after following a redirect and revert data uri support</li>\n<li><a href=\"https://github.com/node-fetch/node-fetch/commit/8c197f8982a238b3c345c64b17bfa92e16b4f7c4\"><code>8c197f8</code></a> docs: Fix typos and grammatical errors in README.md (<a href=\"https://github-redirect.dependabot.com/bitinn/node-fetch/issues/686\">#686</a>)</li>\n<li><a href=\"https://github.com/node-fetch/node-fetch/commit/1e99050f944ac435fce26a9549eadcc2419a968a\"><code>1e99050</code></a> fix: Change error message thrown with redirect mode set to error (<a href=\"https://github-redirect.dependabot.com/bitinn/node-fetch/issues/653\">#653</a>)</li>\n<li><a href=\"https://github.com/node-fetch/node-fetch/commit/244e6f63d42025465796e3ca4ce813bf2c31fc5b\"><code>244e6f6</code></a> docs: Show backers in README</li>\n<li><a href=\"https://github.com/node-fetch/node-fetch/commit/6a5d192034a0f438551dffb6d2d8df2c00921d16\"><code>6a5d192</code></a> fix: Properly parse meta tag when parameters are reversed (<a href=\"https://github-redirect.dependabot.com/bitinn/node-fetch/issues/682\">#682</a>)</li>\n<li><a href=\"https://github.com/node-fetch/node-fetch/commit/47a24a03eb49a49d81b768892aee10074ed54a91\"><code>47a24a0</code></a> chore: Add opencollective badge</li>\n<li><a href=\"https://github.com/node-fetch/node-fetch/commit/7b136627c537cb24430b0310638c9177a85acee1\"><code>7b13662</code></a> chore: Add funding link</li>\n<li><a href=\"https://github.com/node-fetch/node-fetch/commit/5535c2ed478d418969ecfd60c16453462de2a53f\"><code>5535c2e</code></a> fix: Check for global.fetch before binding it (<a href=\"https://github-redirect.dependabot.com/bitinn/node-fetch/issues/674\">#674</a>)</li>\n<li><a href=\"https://github.com/node-fetch/node-fetch/commit/1d5778ad0d910dbd1584fb407a186f5a0bc1ea22\"><code>1d5778a</code></a> docs: Add Discord badge</li>\n<li>Additional commits viewable in <a href=\"https://github.com/bitinn/node-fetch/compare/v1.6.3...v2.6.1\">compare view</a></li>\n</ul>\n</details>\n<details>\n<summary>Maintainer changes</summary>\n<p>This version was pushed to npm by <a href=\"https://www.npmjs.com/~akepinski\">akepinski</a>, a new releaser for node-fetch since your current version.</p>\n</details>\n<br />\n\n\n[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=node-fetch&package-manager=npm_and_yarn&previous-version=1.6.3&new-version=2.6.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/configuring-github-dependabot-security-updates)\n\nDependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.\n\n[//]: # (dependabot-automerge-start)\n[//]: # (dependabot-automerge-end)\n\n---\n\n<details>\n<summary>Dependabot commands and options</summary>\n<br />\n\nYou can trigger Dependabot actions by commenting on this PR:\n- `@dependabot rebase` will rebase this PR\n- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it\n- `@dependabot merge` will merge this PR after your CI passes on it\n- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it\n- `@dependabot cancel merge` will cancel a previously requested merge and block automerging\n- `@dependabot reopen` will reopen this PR if it is closed\n- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually\n- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)\n- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)\n- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)\n- `@dependabot use these labels` will set the current labels as the default for future PRs for this repo and language\n- `@dependabot use these reviewers` will set the current reviewers as the default for future PRs for this repo and language\n- `@dependabot use these assignees` will set the current assignees as the default for future PRs for this repo and language\n- `@dependabot use this milestone` will set the current milestone as the default for future PRs for this repo and language\n\nYou can disable automated security fix PRs for this repo from the [Security Alerts page](https://github.com/facebook/react/network/alerts).\n\n</details>",
        "performed_via_github_app": null
    }
];

export default mockList;